# docker-compose.yml
version: '3'

services:
    phpunit:
      container_name: phpunit
      image: php:8.1.4-cli
      volumes:
        - ..:/app
      working_dir: /app
      entrypoint: bin/phpunit

    php:
      container_name: php
      image: php:8.1.4-fpm
      ports:
        - '9000:9000'
      volumes:
        - ../:/var/www/foodstuffs-api

    nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
        - '80:80'
      volumes:
        - ../:/var/www/foodstuffs-api
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
