# docker-compose.yml
version: '3'

services:
    phpunit:
      container_name: phpunit
      build:
        context: .
        dockerfile: ./php/Dockerfile
      volumes:
        - ..:/app
      working_dir: /app
      entrypoint: bin/phpunit
      depends_on:
        - mariadb_test

    mariadb_test:
      container_name: mariadb_test
      image: mariadb:10.8.2-rc
      restart: always
      ports:
        - '3306:3306'
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: myuserpassword
        MYSQL_DATABASE: foodstuffs_database
        MYSQL_ROOT_PASSWORD: myrootpassword

    mariadb:
      container_name: mariadb
      image: mariadb:10.8.2-rc
      restart: always
      ports:
        - '3306:3306'
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: myuserpassword
        MYSQL_DATABASE: foodstuffs_database
        MYSQL_ROOT_PASSWORD: myrootpassword

    # docker-compose run mariadb_client
    mariadb_client:
      container_name: mariadb_client
      image: mariadb:10.8.2-rc
      restart: 'no'
      command: 'mysql -hmariadb -uuser -pmyuserpassword foodstuffs_database'
      depends_on:
        - mariadb

    php:
      container_name: php
      build:
        context: .
        dockerfile: ./php/Dockerfile
      ports:
        - '9000:9000'
      volumes:
        - ../:/var/www/foodstuffs-api
      command: 'php-fpm'
      depends_on:
        - mariadb

    nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
        - '80:80'
      volumes:
        - ../:/var/www/foodstuffs-api
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mariadb

    db_migration:
      container_name: db_migration
      build:
        context: .
        dockerfile: ./php/Dockerfile
      volumes:
        - ..:/app
      working_dir: /app
      entrypoint: 'bin/console doctrine:migrations:migrate --no-interaction'