#index:
#    path: /
#    controller: App\Controller\DefaultController::index

search_foodstuffs:
    path: /search/name
    controller: App\Controller\ListFoodStuffsController::search

add_to_wishlist_of_foodstuffs:
    path: /add/{ean}
    controller: App\Controller\WishlistOfFoodStuffsController::add