#index:
#    path: /
#    controller: App\Controller\DefaultController::index

search_foodstuffs:
    path: /search/name
    controller: App\Controller\ListFoodStuffsController::search

add_to_wishlist_of_foodstuffs:
    path: /add/{ean}
    controller: App\Controller\WishlistOfFoodStuffsController::add

delete_to_wishlist_of_foodstuffs:
    path: /delete/{ean}
    controller: App\Controller\WishlistOfFoodStuffsController::delete

clear_wishlist_of_foodstuffs:
    path: /clear
    controller: App\Controller\WishlistOfFoodStuffsController::clear

exclude_a_foodstuffs:
    path: /exclude/{ean}
    controller: App\Controller\ExclusionOfFoodStuffsController::exclude