services:
    App\Controller\ListFoodStuffsController:
        arguments: [ '@App\Controller\tests\fixtures\FoodStuffsFixturesRepository' ]
        public: true
        calls:
            - [ setContainer, [ '@service_container' ]]

    App\Controller\WishlistOfFoodStuffsController:
        arguments: [ '@App\Adapter\Wishlist\WishlistOfFoodstuffsMariaDbRepository', '@App\Controller\tests\fixtures\FoodStuffsFixturesRepository' ]
        public: true
        calls:
            - [ setContainer, [ '@service_container' ]]

    App\Controller\ExclusionOfFoodStuffsController:
        arguments: [ '@App\Adapter\ExclusionOfFoodStuffs\ExclusionOfFoodstuffsMariaDbRepository', '@App\Controller\tests\fixtures\FoodStuffsFixturesRepository' ]
        public: true
        calls:
            - [ setContainer, [ '@service_container' ]]