services:
    App\Controller\ListFoodStuffsController:
        arguments: [ '@App\Controller\tests\fixtures\FoodStuffsFixturesRepository' ]
        public: true
        calls:
            - [ setContainer, [ '@service_container' ]]
